openapi: 3.0.1
info:
  title: employments_backend
  description: employments_backend
  version: 1.0.0

paths:
  /employments/calendar:
    get:
      tags:
        - employments
      operationId: getEmploymentCalendar
      parameters:
        - name: project_name
          in: query
          required: true
          schema:
            type: string
        - name: begin_date
          in: query
          required: true
          schema:
            type: string
        - name: egar_id
          in: query
          required: true
          schema:
            type: string
        - name: profile_list_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/EmploymentCalendarDto'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ViolationDto'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiErrorDto'
  /employments:
    get:
      tags:
        - employments
      operationId: getEmploymentsByIds
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmploymentDto'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ViolationDto'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiErrorDto'
components:
  schemas:
    ApiErrorDto:
      type: object
      properties:
        message:
          type: string
        milliseconds:
          type: string
        class:
          type: string
    ViolationDto:
      type: object
      properties:
        field_name:
          type: string
        message:
          type: string
    EmploymentCalendarDto:
      type: object
      properties:
        project_name:
          type: string
        work_calendar:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              $ref: '#/components/schemas/HoursDto'
    HoursDto:
      type: object
      properties:
        work_hours:
          type: integer
          format: int32
        registered_hours:
          type: number
          format: double
    EmploymentDto:
      type: object
      properties:
        project_name:
          type: string
        begin_date:
          type: string